version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: project_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./apps/backend
    container_name: project_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/project_db
    depends_on:
      - postgres

  frontend:
    build: ./apps/frontend
    container_name: project_frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
